"""Seeded passive workload generators for LETIndex-Ref-v1 (EXPERIMENTAL EXTENSION).

The passive baseline means the attacker does **not** choose query keys: queries are
drawn by an experiment-side generator and the plaintext keys stay evaluator-only.

Provenance rule (decision 0009): the pinned upstream repository *references*
workload files that are **not shipped**, so these generators are ours.  They are
never claimed to be the original workload distribution ``c``; the upstream names
may be kept only as provenance metadata.

Modes:

```text
record_uniform   choose uniformly among existing records/keys
domain_uniform   choose uniformly over a declared key domain [lo, hi)
data_empirical   sample from a supplied empirical/query distribution
```

Everything is seeded and reproducible, and no mode is an attack: this module only
*generates* the passive workload.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Mapping, Optional, Sequence

from .letindex_ref import EXPERIMENTAL_EXTENSION

__all__ = [
    "WORKLOAD_RECORD_UNIFORM",
    "WORKLOAD_DOMAIN_UNIFORM",
    "WORKLOAD_DATA_EMPIRICAL",
    "WORKLOAD_MODES",
    "UPSTREAM_WORKLOAD_NOTE",
    "PassiveWorkload",
    "WorkloadError",
    "generate_passive_workload",
]

WORKLOAD_RECORD_UNIFORM = "record_uniform"
WORKLOAD_DOMAIN_UNIFORM = "domain_uniform"
WORKLOAD_DATA_EMPIRICAL = "data_empirical"
WORKLOAD_MODES = (
    WORKLOAD_RECORD_UNIFORM,
    WORKLOAD_DOMAIN_UNIFORM,
    WORKLOAD_DATA_EMPIRICAL,
)

#: Explicit provenance: the upstream repository does not ship its workload ``c``.
UPSTREAM_WORKLOAD_NOTE = (
    "generated by our seeded passive workload generator (EXPERIMENTAL EXTENSION); "
    "the pinned upstream repository references workload files that are not shipped, "
    "so this is NOT the original upstream workload distribution c"
)


class WorkloadError(Exception):
    """The requested passive workload is not well defined."""


@dataclass(frozen=True)
class PassiveWorkload:
    """A seeded passive query workload.  The query keys are evaluator-only."""

    mode: str
    seed: int
    queries: tuple[int, ...]
    record_count: int
    domain: Optional[tuple[int, int]] = None
    provenance: str = UPSTREAM_WORKLOAD_NOTE
    classification: str = EXPERIMENTAL_EXTENSION

    @property
    def count(self) -> int:
        return len(self.queries)

    @property
    def distinct_count(self) -> int:
        return len(set(self.queries))

    def to_dict(self) -> dict:
        """Evaluator-side description **including** the plaintext query keys."""
        return {
            "mode": self.mode,
            "seed": self.seed,
            "count": self.count,
            "distinct_count": self.distinct_count,
            "record_count": self.record_count,
            "domain": list(self.domain) if self.domain else None,
            "provenance": self.provenance,
            "classification": self.classification,
            "queries": list(self.queries),
        }

    def public_dict(self) -> dict:
        """Adversary-safe description: no query keys, no plaintext."""
        return {
            "mode": self.mode,
            "seed": self.seed,
            "count": self.count,
            "distinct_count": self.distinct_count,
            "record_count": self.record_count,
            "domain": list(self.domain) if self.domain else None,
            "provenance": self.provenance,
            "classification": self.classification,
        }


def generate_passive_workload(
    mode: str,
    *,
    seed: int,
    count: int,
    records: Sequence[int] = (),
    domain: Optional[tuple[int, int]] = None,
    empirical: Optional[Mapping[int, float]] = None,
    provenance: Optional[str] = None,
) -> PassiveWorkload:
    """Draw ``count`` query keys with the named seeded passive mode."""
    if mode not in WORKLOAD_MODES:
        raise WorkloadError(
            f"unknown workload mode {mode!r}; expected one of {WORKLOAD_MODES}"
        )
    if isinstance(seed, bool) or not isinstance(seed, int):
        raise WorkloadError(f"seed must be an integer, got {seed!r}")
    if isinstance(count, bool) or not isinstance(count, int) or count < 0:
        raise WorkloadError(f"count must be a non-negative integer, got {count!r}")
    note = provenance or UPSTREAM_WORKLOAD_NOTE
    rng = random.Random(seed)
    keys = tuple(sorted(int(key) for key in records))

    if mode == WORKLOAD_RECORD_UNIFORM:
        if not keys:
            raise WorkloadError(
                "record_uniform requires the key set of the existing records"
            )
        queries = tuple(rng.choice(keys) for _ in range(count))
        return PassiveWorkload(
            mode=mode, seed=seed, queries=queries, record_count=len(keys),
            domain=None, provenance=note,
        )

    if mode == WORKLOAD_DOMAIN_UNIFORM:
        if domain is None:
            raise WorkloadError("domain_uniform requires a declared (lo, hi) domain")
        lo, hi = int(domain[0]), int(domain[1])
        if hi <= lo:
            raise WorkloadError(f"domain [{lo}, {hi}) must be non-empty")
        queries = tuple(rng.randrange(lo, hi) for _ in range(count))
        return PassiveWorkload(
            mode=mode, seed=seed, queries=queries, record_count=len(keys),
            domain=(lo, hi), provenance=note,
        )

    if empirical is None:
        raise WorkloadError(
            "data_empirical requires a supplied empirical distribution "
            "(mapping key -> non-negative weight)"
        )
    weights = {int(key): float(weight) for key, weight in empirical.items()}
    if not weights:
        raise WorkloadError("data_empirical distribution is empty")
    if any(weight < 0 for weight in weights.values()):
        raise WorkloadError("data_empirical weights must be non-negative")
    if sum(weights.values()) <= 0:
        raise WorkloadError("data_empirical weights must not all be zero")
    population = sorted(weights)
    probabilities = [weights[key] for key in population]
    queries = tuple(rng.choices(population, weights=probabilities, k=count))
    return PassiveWorkload(
        mode=mode, seed=seed, queries=queries, record_count=len(keys),
        domain=None, provenance=note,
    )
